language: cpp
compiler: gcc
# ^ tool chain to use for compilation,
#   almost anywhere.
matrix:
  include:
    - os: linux
      before_install:
        - echo "$(lsb_release -d | sed -r 's/^\w+:(\s+)?//') ($(uname -rs))"
        - sudo apt-get install portaudio19-dev libopus-dev libopusfile-dev
      install: make build
      script: echo "No tests assigned!"

    - os: osx
      before_install:
        - ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" < /dev/null 2> /dev/null
        - brew install opusfile opus portaudio
      install: make build
      script: echo "No tests assigned!"